// app/layout.js
import './globals.css';
import { Toaster } from "@/components/ui/toaster"


export const metadata = {
  title: "Link",
  description: "Generated by create link",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          {children}
          <Toaster />
      </body>
    </html>
  );
}
